name: "Reset HEAD of develop to master"

on:
  pull_request:
    types: [ closed ]
    branches:
      - test-rebase

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git environment
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git reset --hard origin/test-rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'test-develop'


